zuul:
    routes:
        ## By default, all requests to user service for example will start with: "/user/"
        ## What will be sent to the user service is what comes after the path defined,
        ## So, if request is "/user/v1/user/tedkim", user service will get "/v1/user/tedkim".
        treequery-service-A:
            path: /treequery-A/**
            service-id: TreeQueryNodeGrpc-Service-A
        treequery-service-B:
            path: /treequery-B/**
            service-id: TreeQueryNodeGrpc-Service-B
        treequery-service-C:
            path: /treequery-C/**
            service-id: TreeQueryNodeGrpc-Service-C