spring:
  application:
    name: EurekaClient
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8082
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}